### PR TITLE
Updates from Overleaf

### PR DESCRIPTION
**Pull request by vmonardo**

### CODE REVIEW

**Comment by vmonardo** [comment]
Hi @shensquared following up on your issue. (sorry if this is not best Github etiquette)

I believe I have resolved the conflicts between the Overleaf and the main in the Github repo. In particular, the transformers.tex file was out of sync.

Could you sanity check me and accept the pull request if it seems reasonable?

**Comment by shensquared** [comment]
I encountered a few issues:

1. The main `top.tex` doesn't compile. Seemingly due to a couple syntax error; fixed.

2. Also fixed the sidenote rendering issue raised in #4, I think. Would be good to see if the fix reproduces on other machines.

3. I disagree with commit a20e54ca4485df64096f7676f84b5c92cccb4589 --  unsupervised learning can certainly have ground truth groups (just not labels). I explained my thinking in details at https://github.com/390introml/introml-notes-tex/pull/2#discussion_r1839282640 but happy to discuss more.

**Comment by vmonardo** [comment]
Hi Shen,

`top.tex` builds for me. I believe the previous rendering issue was due to compiling only once and not twice. (In particular, I pulled after "side note fix" and compiled once to rendering error, recompiled and rendering error is fixed). In clustering.tex, I intended to write "However, we do not always expect this to be the case." I've just removed that since that assumption is already being made at the start of the paragraph. 

Let me know what you think.

**Comment by shensquared** [comment]
I agree with removing that sentence. 

Good to know the fix worked. 

I'll go ahead and merge. Thanks.

**Pull request merged**
